export const countries = [
  {
    name: "Germany",
    dialCode: "+49",
    code: "DE",
    flag: "https://flagsapi.com/DE/flat/64.png",
  },
  {
    name: "Bulgaria",
    dialCode: "+359",
    code: "BG",
    flag: "https://flagsapi.com/BG/flat/64.png",
  },
  {
    name: "Slovakia",
    dialCode: "+421",
    code: "SK",
    flag: "https://flagsapi.com/SK/flat/64.png",
  },
  {
    name: "Hungary",
    dialCode: "+36",
    code: "HU",
    flag: "https://flagsapi.com/HU/flat/64.png",
  },
  {
    name: "Belgium",
    dialCode: "+32",
    code: "BE",
    flag: "https://flagsapi.com/BE/flat/64.png",
  },
  {
    name: "Martinique",
    dialCode: "+596",
    code: "MQ",
    flag: "https://flagsapi.com/MQ/flat/64.png",
  },
  {
    name: "New Zealand",
    dialCode: "+64",
    code: "NZ",
    flag: "https://flagsapi.com/NZ/flat/64.png",
  },
  {
    name: "Gibraltar",
    dialCode: "+350",
    code: "GI",
    flag: "https://flagsapi.com/GI/flat/64.png",
  },
  {
    name: "Zimbabwe",
    dialCode: "+263",
    code: "ZW",
    flag: "https://flagsapi.com/ZW/flat/64.png",
  },
  {
    name: "Guam",
    dialCode: "+1671",
    code: "GU",
    flag: "https://flagsapi.com/GU/flat/64.png",
  },
  {
    name: "Namibia",
    dialCode: "+264",
    code: "NA",
    flag: "https://flagsapi.com/NA/flat/64.png",
  },
  {
    name: "Canada",
    dialCode: "+1",
    code: "CM",
    flag: "https://flagsapi.com/CA/flat/64.png",
  },
  {
    name: "Cameroon",
    dialCode: "+237",
    code: "KH",
    flag: "https://flagsapi.com/KH/flat/64.png",
  },
  {
    name: "Greenland",
    dialCode: "+299",
    code: "GL",
    flag: "https://flagsapi.com/GL/flat/64.png",
  },
  {
    name: "Antigua and Barbuda",
    dialCode: "+1268",
    code: "AG",
    flag: "https://flagsapi.com/AG/flat/64.png",
  },
  {
    name: "Saint Martin",
    dialCode: "+590",
    code: "MF",
    flag: "https://flagsapi.com/MF/flat/64.png",
  },
  {
    name: "Libya",
    dialCode: "",
    code: "LY",
    flag: "https://flagsapi.com/LY/flat/64.png",
  },
  {
    name: "Italy",
    dialCode: "+39",
    code: "IT",
    flag: "https://flagsapi.com/IT/flat/64.png",
  },
  {
    name: "Japan",
    dialCode: "+81",
    code: "JP",
    flag: "https://flagsapi.com/JP/flat/64.png",
  },
  {
    name: "Egypt",
    dialCode: "+20",
    code: "EG",
    flag: "https://flagsapi.com/EG/flat/64.png",
  },
  {
    name: "Philippines",
    dialCode: "+63",
    code: "PH",
    flag: "https://flagsapi.com/PH/flat/64.png",
  },
  {
    name: "Cabo Verde",
    dialCode: "",
    code: "CI",
    flag: "https://flagsapi.com/CI/flat/64.png",
  },
  {
    name: "Kazakhstan",
    dialCode: "+77",
    code: "KZ",
    flag: "https://flagsapi.com/KZ/flat/64.png",
  },
  {
    name: "Malaysia",
    dialCode: "+60",
    code: "MY",
    flag: "https://flagsapi.com/MY/flat/64.png",
  },
  {
    name: "Turkmenistan",
    dialCode: "+993",
    code: "TM",
    flag: "https://flagsapi.com/TM/flat/64.png",
  },
  {
    name: "Tunisia",
    dialCode: "+216",
    code: "TN",
    flag: "https://flagsapi.com/TN/flat/64.png",
  },
  {
    name: "Paraguay",
    dialCode: "+595",
    code: "PY",
    flag: "https://flagsapi.com/PY/flat/64.png",
  },
  {
    name: "Mozambique",
    dialCode: "+258",
    code: "MZ",
    flag: "https://flagsapi.com/MZ/flat/64.png",
  },
  {
    name: "Gambia",
    dialCode: "+220",
    code: "GM",
    flag: "https://flagsapi.com/GM/flat/64.png",
  },
  {
    name: "New Caledonia",
    dialCode: "+687",
    code: "NC",
    flag: "https://flagsapi.com/NC/flat/64.png",
  },
  {
    name: "French Polynesia",
    dialCode: "+689",
    code: "PF",
    flag: "https://flagsapi.com/PF/flat/64.png",
  },
  {
    name: "Trinidad and Tobago",
    dialCode: "+1868",
    code: "TT",
    flag: "https://flagsapi.com/TT/flat/64.png",
  },
  {
    name: "Nepal",
    dialCode: "+977",
    code: "NP",
    flag: "https://flagsapi.com/NP/flat/64.png",
  },
  {
    name: "Bangladesh",
    dialCode: "+880",
    code: "BD",
    flag: "https://flagsapi.com/BD/flat/64.png",
  },
  {
    name: "Lesotho",
    dialCode: "+266",
    code: "LS",
    flag: "https://flagsapi.com/LS/flat/64.png",
  },
  {
    name: "Ghana",
    dialCode: "+233",
    code: "GH",
    flag: "https://flagsapi.com/GH/flat/64.png",
  },
  {
    name: "Belarus",
    dialCode: "+375",
    code: "BY",
    flag: "https://flagsapi.com/BY/flat/64.png",
  },
  {
    name: "China",
    dialCode: "+86",
    code: "CL",
    flag: "https://flagsapi.com/CN/flat/64.png",
  },
  {
    name: "Montenegro",
    dialCode: "+382",
    code: "ME",
    flag: "https://flagsapi.com/ME/flat/64.png",
  },
  {
    name: "Mayotte",
    dialCode: "+262",
    code: "YT",
    flag: "https://flagsapi.com/YT/flat/64.png",
  },
  {
    name: "Ireland",
    dialCode: "+353",
    code: "IE",
    flag: "https://flagsapi.com/IE/flat/64.png",
  },
  {
    name: "Albania",
    dialCode: "+355",
    code: "AL",
    flag: "https://flagsapi.com/AL/flat/64.png",
  },
  {
    name: "Liberia",
    dialCode: "+231",
    code: "LR",
    flag: "https://flagsapi.com/LR/flat/64.png",
  },
  {
    name: "Turks and Caicos",
    dialCode: "",
    code: "TC",
    flag: "https://flagsapi.com/TC/flat/64.png",
  },
  {
    name: "Angola",
    dialCode: "+244",
    code: "AO",
    flag: "https://flagsapi.com/AO/flat/64.png",
  },
  {
    name: "St. Vincent & Grenadines",
    dialCode: "",
    code: "VC",
    flag: "https://flagsapi.com/VC/flat/64.png",
  },
  {
    name: "Colombia",
    dialCode: "+57",
    code: "CN",
    flag: "https://flagsapi.com/CO/flat/64.png",
  },
  {
    name: "Seychelles",
    dialCode: "+248",
    code: "SC",
    flag: "https://flagsapi.com/SC/flat/64.png",
  },
  {
    name: "Andorra",
    dialCode: "+376",
    code: "AD",
    flag: "https://flagsapi.com/AD/flat/64.png",
  },
  {
    name: "Venezuela",
    dialCode: "",
    code: "VE",
    flag: "https://flagsapi.com/VE/flat/64.png",
  },
  {
    name: "Iraq",
    dialCode: "+964",
    code: "IQ",
    flag: "https://flagsapi.com/IQ/flat/64.png",
  },
  {
    name: "Timor-Leste",
    dialCode: "+670",
    code: "TL",
    flag: "https://flagsapi.com/TL/flat/64.png",
  },
  {
    name: "DR Congo",
    dialCode: "",
    code: "CD",
    flag: "https://flagsapi.com/CD/flat/64.png",
  },
  {
    name: "Slovenia",
    dialCode: "+386",
    code: "SI",
    flag: "https://flagsapi.com/SI/flat/64.png",
  },
  {
    name: "Eswatini",
    dialCode: "",
    code: "SZ",
    flag: "https://flagsapi.com/SZ/flat/64.png",
  },
  {
    name: "Dominica",
    dialCode: "+1767",
    code: "DM",
    flag: "https://flagsapi.com/DM/flat/64.png",
  },
  {
    name: "Zambia",
    dialCode: "+260",
    code: "ZM",
    flag: "https://flagsapi.com/ZM/flat/64.png",
  },
  {
    name: "Vanuatu",
    dialCode: "+678",
    code: "VU",
    flag: "https://flagsapi.com/VU/flat/64.png",
  },
  {
    name: "Cura?ao",
    dialCode: "",
    code: "CW",
    flag: "https://flagsapi.com/CW/flat/64.png",
  },
  {
    name: "Iceland",
    dialCode: "+354",
    code: "IS",
    flag: "https://flagsapi.com/IS/flat/64.png",
  },
  {
    name: "United Arab Emirates",
    dialCode: "+971",
    code: "AE",
    flag: "https://flagsapi.com/AE/flat/64.png",
  },
  {
    name: "Nauru",
    dialCode: "+674",
    code: "NR",
    flag: "https://flagsapi.com/NR/flat/64.png",
  },
  {
    name: "Syria",
    dialCode: "",
    code: "SY",
    flag: "https://flagsapi.com/SY/flat/64.png",
  },
  {
    name: "Mali",
    dialCode: "+223",
    code: "ML",
    flag: "https://flagsapi.com/ML/flat/64.png",
  },
  {
    name: "Sierra Leone",
    dialCode: "+232",
    code: "SL",
    flag: "https://flagsapi.com/SL/flat/64.png",
  },
  {
    name: "Sri Lanka",
    dialCode: "+94",
    code: "LK",
    flag: "https://flagsapi.com/LK/flat/64.png",
  },
  {
    name: "Burundi",
    dialCode: "+257",
    code: "BI",
    flag: "https://flagsapi.com/BI/flat/64.png",
  },
  {
    name: "Bosnia and Herzegovina",
    dialCode: "+387",
    code: "BA",
    flag: "https://flagsapi.com/BA/flat/64.png",
  },
  {
    name: "Holy See",
    dialCode: "",
    code: "VA",
    flag: "https://flagsapi.com/VA/flat/64.png",
  },
  {
    name: "Fiji",
    dialCode: "+679",
    code: "FJ",
    flag: "https://flagsapi.com/FJ/flat/64.png",
  },
  {
    name: "Mexico",
    dialCode: "+52",
    code: "MX",
    flag: "https://flagsapi.com/MX/flat/64.png",
  },
  {
    name: "Macao",
    dialCode: "+853",
    code: "MO",
    flag: "https://flagsapi.com/MO/flat/64.png",
  },
  {
    name: "Hong Kong",
    dialCode: "+852",
    code: "HK",
    flag: "https://flagsapi.com/HK/flat/64.png",
  },
  {
    name: "South Sudan",
    dialCode: "+211",
    code: "SS",
    flag: "https://flagsapi.com/SS/flat/64.png",
  },
  {
    name: "Kuwait",
    dialCode: "+965",
    code: "KW",
    flag: "https://flagsapi.com/KW/flat/64.png",
  },
  {
    name: "Tajikistan",
    dialCode: "+992",
    code: "TJ",
    flag: "https://flagsapi.com/TJ/flat/64.png",
  },
  {
    name: "Norway",
    dialCode: "+47",
    code: "NO",
    flag: "https://flagsapi.com/NO/flat/64.png",
  },
  {
    name: "Nicaragua",
    dialCode: "+505",
    code: "NI",
    flag: "https://flagsapi.com/NI/flat/64.png",
  },
  {
    name: "Laos",
    dialCode: "+856",
    code: "LA",
    flag: "https://flagsapi.com/LA/flat/64.png",
  },
  {
    name: "Chad",
    dialCode: "+235",
    code: "CF",
    flag: "https://flagsapi.com/TD/flat/64.png",
  },
  {
    name: "Uruguay",
    dialCode: "+598",
    code: "UY",
    flag: "https://flagsapi.com/UY/flat/64.png",
  },
  {
    name: "India",
    dialCode: "+91",
    code: "IN",
    flag: "https://flagsapi.com/IN/flat/64.png",
  },
  {
    name: "Guyana",
    dialCode: "+595",
    code: "GY",
    flag: "https://flagsapi.com/GY/flat/64.png",
  },
  {
    name: "Bhutan",
    dialCode: "+975",
    code: "BT",
    flag: "https://flagsapi.com/BT/flat/64.png",
  },
  {
    name: "Tonga",
    dialCode: "+676",
    code: "TO",
    flag: "https://flagsapi.com/TO/flat/64.png",
  },
  {
    name: "Armenia",
    dialCode: "+374",
    code: "AM",
    flag: "https://flagsapi.com/AM/flat/64.png",
  },
  {
    name: "Afghanistan",
    dialCode: "+93",
    code: "AF",
    flag: "https://flagsapi.com/AF/flat/64.png",
  },
  {
    name: "British Virgin Islands",
    dialCode: "",
    code: "VG",
    flag: "https://flagsapi.com/VG/flat/64.png",
  },
  {
    name: "Puerto Rico",
    dialCode: "+1939",
    code: "PR",
    flag: "https://flagsapi.com/PR/flat/64.png",
  },
  {
    name: "Estonia",
    dialCode: "+372",
    code: "EE",
    flag: "https://flagsapi.com/EE/flat/64.png",
  },
  {
    name: "Mauritius",
    dialCode: "+230",
    code: "MU",
    flag: "https://flagsapi.com/MU/flat/64.png",
  },
  {
    name: "Rwanda",
    dialCode: "+250",
    code: "RW",
    flag: "https://flagsapi.com/RW/flat/64.png",
  },
  {
    name: "Aruba",
    dialCode: "+297",
    code: "AW",
    flag: "https://flagsapi.com/AW/flat/64.png",
  },
  {
    name: "C?te dIvoire",
    dialCode: "",
    code: "HR",
    flag: "https://flagsapi.com/HR/flat/64.png",
  },
  {
    name: "Liechtenstein",
    dialCode: "+423",
    code: "LI",
    flag: "https://flagsapi.com/LI/flat/64.png",
  },
  {
    name: "Faeroe Islands",
    dialCode: "",
    code: "FO",
    flag: "https://flagsapi.com/FO/flat/64.png",
  },
  {
    name: "Thailand",
    dialCode: "+66",
    code: "TH",
    flag: "https://flagsapi.com/TH/flat/64.png",
  },
  {
    name: "Tanzania",
    dialCode: "",
    code: "TZ",
    flag: "https://flagsapi.com/TZ/flat/64.png",
  },
  {
    name: "Western Sahara",
    dialCode: "",
    code: "EH",
    flag: "https://flagsapi.com/EH/flat/64.png",
  },
  {
    name: "Myanmar",
    dialCode: "+95",
    code: "MM",
    flag: "https://flagsapi.com/MM/flat/64.png",
  },
  {
    name: "Somalia",
    dialCode: "+252",
    code: "SO",
    flag: "https://flagsapi.com/SO/flat/64.png",
  },
  {
    name: "Saint Lucia",
    dialCode: "+1758",
    code: "LC",
    flag: "https://flagsapi.com/LC/flat/64.png",
  },
  {
    name: "Uzbekistan",
    dialCode: "+998",
    code: "UZ",
    flag: "https://flagsapi.com/UZ/flat/64.png",
  },
  {
    name: "French Guiana",
    dialCode: "+594",
    code: "GF",
    flag: "https://flagsapi.com/FR/flat/64.png",
  },
  {
    name: "San Marino",
    dialCode: "+378",
    code: "SM",
    flag: "https://flagsapi.com/SM/flat/64.png",
  },
  {
    name: "Kyrgyzstan",
    dialCode: "+996",
    code: "KG",
    flag: "https://flagsapi.com/KG/flat/64.png",
  },
  {
    name: "Bermuda",
    dialCode: "+1441",
    code: "BM",
    flag: "https://flagsapi.com/BM/flat/64.png",
  },
  {
    name: "Sao Tome & Principe",
    dialCode: "",
    code: "ST",
    flag: "https://flagsapi.com/ST/flat/64.png",
  },
  {
    name: "Comoros",
    dialCode: "+269",
    code: "CO",
    flag: "https://flagsapi.com/KM/flat/64.png",
  },
  {
    name: "South Africa",
    dialCode: "+27",
    code: "ZA",
    flag: "https://flagsapi.com/ZA/flat/64.png",
  },
  {
    name: "Suriname",
    dialCode: "+597",
    code: "SR",
    flag: "https://flagsapi.com/SR/flat/64.png",
  },
  {
    name: "Samoa",
    dialCode: "+685",
    code: "WS",
    flag: "https://flagsapi.com/WS/flat/64.png",
  },
  {
    name: "Bahrain",
    dialCode: "+973",
    code: "BH",
    flag: "https://flagsapi.com/BH/flat/64.png",
  },
  {
    name: "Channel Islands",
    dialCode: "",
    code: "TD",
    flag: "https://flagsapi.com/GB/flat/64.png",
  },
  {
    name: "Yemen",
    dialCode: "+967",
    code: "YE",
    flag: "https://flagsapi.com/YE/flat/64.png",
  },
  {
    name: "Saint Pierre & Miquelon",
    dialCode: "",
    code: "PM",
    flag: "https://firebasestorage.googleapis.com/v0/b/bean-trader-exclusivity.appspot.com/o/cms_uploads%2Fexclusivity_countries%2F1690944691256000%2Fsaint_pierre.png?alt=media&token=d5d326e1-ae4c-4b80-a3e8-6c8d4f49bace",
  },
  {
    name: "Guinea",
    dialCode: "+224",
    code: "GN",
    flag: "https://flagsapi.com/GN/flat/64.png",
  },
  {
    name: "Honduras",
    dialCode: "+504",
    code: "HN",
    flag: "https://flagsapi.com/HN/flat/64.png",
  },
  {
    name: "Senegal",
    dialCode: "+221",
    code: "SN",
    flag: "https://flagsapi.com/SN/flat/64.png",
  },
  {
    name: "R?union",
    dialCode: "",
    code: "RO",
    flag: "https://flagsapi.com/RO/flat/64.png",
  },
  {
    name: "Portugal",
    dialCode: "+351",
    code: "PT",
    flag: "https://flagsapi.com/PT/flat/64.png",
  },
  {
    name: "Marshall Islands",
    dialCode: "+692",
    code: "MH",
    flag: "https://flagsapi.com/MH/flat/64.png",
  },
  {
    name: "Benin",
    dialCode: "+229",
    code: "BJ",
    flag: "https://flagsapi.com/BJ/flat/64.png",
  },
  {
    name: "Congo",
    dialCode: "+242",
    code: "KM",
    flag: "https://flagsapi.com/KM/flat/64.png",
  },
  {
    name: "Isle of Man",
    dialCode: "+44",
    code: "IM",
    flag: "https://flagsapi.com/IM/flat/64.png",
  },
  {
    name: "Austria",
    dialCode: "+43",
    code: "AT",
    flag: "https://flagsapi.com/AT/flat/64.png",
  },
  {
    name: "Ethiopia",
    dialCode: "+251",
    code: "ET",
    flag: "https://flagsapi.com/ET/flat/64.png",
  },
  {
    name: "Serbia",
    dialCode: "+381",
    code: "RS",
    flag: "https://flagsapi.com/RS/flat/64.png",
  },
  {
    name: "Solomon Islands",
    dialCode: "+677",
    code: "SB",
    flag: "https://flagsapi.com/SB/flat/64.png",
  },
  {
    name: "Northern Mariana Islands",
    dialCode: "+1670",
    code: "MP",
    flag: "https://flagsapi.com/MP/flat/64.png",
  },
  {
    name: "Saint Kitts & Nevis",
    dialCode: "",
    code: "KN",
    flag: "https://flagsapi.com/KN/flat/64.png",
  },
  {
    name: "Ukraine",
    dialCode: "+380",
    code: "UA",
    flag: "https://flagsapi.com/UA/flat/64.png",
  },
  {
    name: "Cambodia",
    dialCode: "+855",
    code: "CV",
    flag: "https://flagsapi.com/CV/flat/64.png",
  },
  {
    name: "Oman",
    dialCode: "+968",
    code: "OM",
    flag: "https://flagsapi.com/OM/flat/64.png",
  },
  {
    name: "Qatar",
    dialCode: "+974",
    code: "QA",
    flag: "https://flagsapi.com/QA/flat/64.png",
  },
  {
    name: "Azerbaijan",
    dialCode: "+994",
    code: "AZ",
    flag: "https://flagsapi.com/AZ/flat/64.png",
  },
  {
    name: "Togo",
    dialCode: "+228",
    code: "TG",
    flag: "https://flagsapi.com/TG/flat/64.png",
  },
  {
    name: "Guinea-Bissau",
    dialCode: "+245",
    code: "GW",
    flag: "https://flagsapi.com/GW/flat/64.png",
  },
  {
    name: "Saint Barthelemy",
    dialCode: "+590",
    code: "BL",
    flag: "https://firebasestorage.googleapis.com/v0/b/bean-trader-exclusivity.appspot.com/o/cms_uploads%2Fexclusivity_countries%2F1690944711515000%2Fsaint_barthelemy.png?alt=media&token=4d7f1bfe-d0ae-4c1b-b645-f2188a3b6bd8",
  },
  {
    name: "State of Palestine",
    dialCode: "",
    code: "PS",
    flag: "https://flagsapi.com/PS/flat/64.png",
  },
  {
    name: "Singapore",
    dialCode: "+65",
    code: "SG",
    flag: "https://flagsapi.com/SG/flat/64.png",
  },
  {
    name: "Uganda",
    dialCode: "+256",
    code: "UG",
    flag: "https://flagsapi.com/UG/flat/64.png",
  },
  {
    name: "Micronesia",
    dialCode: "",
    code: "FM",
    flag: "https://flagsapi.com/FM/flat/64.png",
  },
  {
    name: "France",
    dialCode: "+33",
    code: "FR",
    flag: "https://flagsapi.com/FR/flat/64.png",
  },
  {
    name: "Grenada",
    dialCode: "+1473",
    code: "GD",
    flag: "https://flagsapi.com/GD/flat/64.png",
  },
  {
    name: "North Macedonia",
    dialCode: "",
    code: "MK",
    flag: "https://flagsapi.com/MK/flat/64.png",
  },
  {
    name: "Barbados",
    dialCode: "+1246",
    code: "BB",
    flag: "https://flagsapi.com/BB/flat/64.png",
  },
  {
    name: "Sudan",
    dialCode: "+249",
    code: "SD",
    flag: "https://flagsapi.com/SD/flat/64.png",
  },
  {
    name: "Burkina Faso",
    dialCode: "+226",
    code: "BF",
    flag: "https://flagsapi.com/BF/flat/64.png",
  },
  {
    name: "Sint Maarten",
    dialCode: "",
    code: "SX",
    flag: "https://firebasestorage.googleapis.com/v0/b/bean-trader-exclusivity.appspot.com/o/cms_uploads%2Fexclusivity_countries%2F1690944132476000%2Fsint_maarten.png?alt=media&token=bcb0a346-3c32-4193-a4d7-1a64927e188b",
  },
  {
    name: "Israel",
    dialCode: "+972",
    code: "IL",
    flag: "https://flagsapi.com/IL/flat/64.png",
  },
  {
    name: "Pakistan",
    dialCode: "+92",
    code: "PK",
    flag: "https://flagsapi.com/PK/flat/64.png",
  },
  {
    name: "Switzerland",
    dialCode: "+41",
    code: "CH",
    flag: "https://flagsapi.com/CH/flat/64.png",
  },
  {
    name: "Papua New Guinea",
    dialCode: "+675",
    code: "PG",
    flag: "https://flagsapi.com/PG/flat/64.png",
  },
  {
    name: "Falkland Islands",
    dialCode: "",
    code: "FK",
    flag: "https://flagsapi.com/FK/flat/64.png",
  },
  {
    name: "U.S. Virgin Islands",
    dialCode: "",
    code: "VI",
    flag: "https://flagsapi.com/VI/flat/64.png",
  },
  {
    name: "Ecuador",
    dialCode: "+593",
    code: "EC",
    flag: "https://flagsapi.com/EC/flat/64.png",
  },
  {
    name: "Lithuania",
    dialCode: "+370",
    code: "LT",
    flag: "https://flagsapi.com/LT/flat/64.png",
  },
  {
    name: "Djibouti",
    dialCode: "+253",
    code: "DJ",
    flag: "https://flagsapi.com/DJ/flat/64.png",
  },
  {
    name: "Cook Islands",
    dialCode: "+682",
    code: "CG",
    flag: "https://flagsapi.com/CK/flat/64.png",
  },
  {
    name: "Niger",
    dialCode: "+227",
    code: "NE",
    flag: "https://flagsapi.com/NE/flat/64.png",
  },
  {
    name: "Taiwan",
    dialCode: "+886",
    code: "TW",
    flag: "https://flagsapi.com/TW/flat/64.png",
  },
  {
    name: "Jamaica",
    dialCode: "+1876",
    code: "JM",
    flag: "https://flagsapi.com/JM/flat/64.png",
  },
  {
    name: "Brunei",
    dialCode: "",
    code: "BN",
    flag: "https://flagsapi.com/BN/flat/64.png",
  },
  {
    name: "Luxembourg",
    dialCode: "+352",
    code: "LU",
    flag: "https://flagsapi.com/LU/flat/64.png",
  },
  {
    name: "Iran",
    dialCode: "",
    code: "IR",
    flag: "https://flagsapi.com/IR/flat/64.png",
  },
  {
    name: "Poland",
    dialCode: "+48",
    code: "PL",
    flag: "https://flagsapi.com/PL/flat/64.png",
  },
  {
    name: "Cyprus",
    dialCode: "+357",
    code: "CY",
    flag: "https://flagsapi.com/CY/flat/64.png",
  },
  {
    name: "Botswana",
    dialCode: "+267",
    code: "BW",
    flag: "https://flagsapi.com/BW/flat/64.png",
  },
  {
    name: "Denmark",
    dialCode: "+45",
    code: "DK",
    flag: "https://flagsapi.com/DK/flat/64.png",
  },
  {
    name: "Panama",
    dialCode: "+507",
    code: "PA",
    flag: "https://flagsapi.com/PA/flat/64.png",
  },
  {
    name: "Indonesia",
    dialCode: "+62",
    code: "ID",
    flag: "https://flagsapi.com/ID/flat/64.png",
  },
  {
    name: "Guatemala",
    dialCode: "+502",
    code: "GT",
    flag: "https://flagsapi.com/GT/flat/64.png",
  },
  {
    name: "Argentina",
    dialCode: "+54",
    code: "AR",
    flag: "https://flagsapi.com/AR/flat/64.png",
  },
  {
    name: "Peru",
    dialCode: "+51",
    code: "PE",
    flag: "https://flagsapi.com/PE/flat/64.png",
  },
  {
    name: "Bolivia",
    dialCode: "",
    code: "BO",
    flag: "https://flagsapi.com/BO/flat/64.png",
  },
  {
    name: "Greece",
    dialCode: "+30",
    code: "GR",
    flag: "https://flagsapi.com/GR/flat/64.png",
  },
  {
    name: "Tuvalu",
    dialCode: "+688",
    code: "TV",
    flag: "https://flagsapi.com/TV/flat/64.png",
  },
  {
    name: "Latvia",
    dialCode: "+371",
    code: "LV",
    flag: "https://flagsapi.com/LV/flat/64.png",
  },
  {
    name: "Sweden",
    dialCode: "+46",
    code: "SE",
    flag: "https://flagsapi.com/SE/flat/64.png",
  },
  {
    name: "Cuba",
    dialCode: "+53",
    code: "CU",
    flag: "https://flagsapi.com/CU/flat/64.png",
  },
  {
    name: "Wallis & Futuna",
    dialCode: "",
    code: "WF",
    flag: "https://flagsapi.com/WF/flat/64.png",
  },
  {
    name: "Morocco",
    dialCode: "+212",
    code: "MA",
    flag: "https://flagsapi.com/MA/flat/64.png",
  },
  {
    name: "Nigeria",
    dialCode: "+234",
    code: "NG",
    flag: "https://flagsapi.com/NG/flat/64.png",
  },
  {
    name: "Brazil",
    dialCode: "+55",
    code: "BR",
    flag: "https://flagsapi.com/BR/flat/64.png",
  },
  {
    name: "Anguilla",
    dialCode: "+1264",
    code: "AI",
    flag: "https://flagsapi.com/AI/flat/64.png",
  },
  {
    name: "Montserrat",
    dialCode: "+1664",
    code: "MS",
    flag: "https://flagsapi.com/MS/flat/64.png",
  },
  {
    name: "Kiribati",
    dialCode: "+686",
    code: "KI",
    flag: "https://flagsapi.com/KI/flat/64.png",
  },
  {
    name: "Spain",
    dialCode: "+34",
    code: "ES",
    flag: "https://flagsapi.com/ES/flat/64.png",
  },
  {
    name: "Vietnam",
    dialCode: "+84",
    code: "VN",
    flag: "https://flagsapi.com/VN/flat/64.png",
  },
  {
    name: "Chile",
    dialCode: "+56",
    code: "JE",
    flag: "https://flagsapi.com/CL/flat/64.png",
  },
  {
    name: "Malawi",
    dialCode: "+265",
    code: "MW",
    flag: "https://flagsapi.com/MW/flat/64.png",
  },
  {
    name: "Saudi Arabia",
    dialCode: "+966",
    code: "SA",
    flag: "https://flagsapi.com/SA/flat/64.png",
  },
  {
    name: "Kenya",
    dialCode: "+254",
    code: "KE",
    flag: "https://flagsapi.com/KE/flat/64.png",
  },
  {
    name: "American Samoa",
    dialCode: "",
    code: "AS",
    flag: "https://flagsapi.com/AS/flat/64.png",
  },
  {
    name: "Guadeloupe",
    dialCode: "+590",
    code: "GP",
    flag: "https://flagsapi.com/FR/flat/64.png",
  },
  {
    name: "South Korea",
    dialCode: "",
    code: "KR",
    flag: "https://flagsapi.com/KR/flat/64.png",
  },
  {
    name: "Monaco",
    dialCode: "+377",
    code: "MC",
    flag: "https://flagsapi.com/MC/flat/64.png",
  },
  {
    name: "Netherlands",
    dialCode: "+31",
    code: "NL",
    flag: "https://flagsapi.com/NL/flat/64.png",
  },
  {
    name: "Caribbean Netherlands",
    dialCode: "",
    code: "CA",
    flag: "https://firebasestorage.googleapis.com/v0/b/bean-trader-exclusivity.appspot.com/o/cms_uploads%2Fexclusivity_countries%2F1692871411011000%2Fbq.png?alt=media&token=ce88c847-340f-48f0-b6b0-dfec5c4ec11a",
  },
  {
    name: "Jordan",
    dialCode: "+962",
    code: "JO",
    flag: "https://flagsapi.com/JO/flat/64.png",
  },
  {
    name: "Maldives",
    dialCode: "+960",
    code: "MV",
    flag: "https://flagsapi.com/MV/flat/64.png",
  },
  {
    name: "Russia",
    dialCode: "+7",
    code: "RU",
    flag: "https://flagsapi.com/RU/flat/64.png",
  },
  {
    name: "Malta",
    dialCode: "+356",
    code: "MT",
    flag: "https://flagsapi.com/MT/flat/64.png",
  },
  {
    name: "United States",
    dialCode: "+1",
    code: "US",
    flag: "https://flagsapi.com/US/flat/64.png",
  },
  {
    name: "Croatia",
    dialCode: "+385",
    code: "CR",
    flag: "https://flagsapi.com/HR/flat/64.png",
  },
  {
    name: "Palau",
    dialCode: "+680",
    code: "PW",
    flag: "https://flagsapi.com/PW/flat/64.png",
  },
  {
    name: "Tokelau",
    dialCode: "+690",
    code: "TK",
    flag: "https://flagsapi.com/TK/flat/64.png",
  },
  {
    name: "North Korea",
    dialCode: "",
    code: "KP",
    flag: "https://flagsapi.com/KP/flat/64.png",
  },
  {
    dialCode: "",
  },
  {
    name: "Madagascar",
    dialCode: "+261",
    code: "MG",
    flag: "https://flagsapi.com/MG/flat/64.png",
  },
  {
    name: "Åland",
    dialCode: "",
    code: "AX",
    flag: "https://flagsapi.com/AX/flat/64.png",
  },
  {
    name: "Australia",
    dialCode: "+61",
    code: "AU",
    flag: "https://flagsapi.com/AU/flat/64.png",
  },
  {
    name: "Guernsey",
    dialCode: "+44",
    code: "GG",
    flag: "https://flagsapi.com/GG/flat/64.png",
  },
  {
    name: "Cayman Islands",
    dialCode: "+ 345",
    code: "BQ",
    flag: "https://firebasestorage.googleapis.com/v0/b/bean-trader-exclusivity.appspot.com/o/cms_uploads%2Fexclusivity_countries%2F1690944775792000%2Fcayman_islands.png?alt=media&token=4d4b0fff-e1e7-4bcb-aea1-20c7a25693f5",
  },
  {
    name: "Georgia",
    dialCode: "+995",
    code: "GE",
    flag: "https://flagsapi.com/GE/flat/64.png",
  },
  {
    name: "Mauritania",
    dialCode: "+222",
    code: "MR",
    flag: "https://flagsapi.com/MR/flat/64.png",
  },
  {
    name: "Saint Helena",
    dialCode: "",
    code: "SH",
    flag: "https://flagsapi.com/SH/flat/64.png",
  },
  {
    name: "Algeria",
    dialCode: "+213",
    code: "DZ",
    flag: "https://flagsapi.com/DZ/flat/64.png",
  },
  {
    name: "Eritrea",
    dialCode: "+291",
    code: "ER",
    flag: "https://flagsapi.com/ER/flat/64.png",
  },
  {
    name: "Equatorial Guinea",
    dialCode: "+240",
    code: "GQ",
    flag: "https://flagsapi.com/GQ/flat/64.png",
  },
  {
    name: "Niue",
    dialCode: "+683",
    code: "NU",
    flag: "https://flagsapi.com/NU/flat/64.png",
  },
  {
    name: "Moldova",
    dialCode: "+373",
    code: "MD",
    flag: "https://flagsapi.com/MD/flat/64.png",
  },
  {
    name: "Turkey",
    dialCode: "+90",
    code: "TR",
    flag: "https://flagsapi.com/TR/flat/64.png",
  },
  {
    name: "Dominican Republic",
    dialCode: "+1849",
    code: "DO",
    flag: "https://flagsapi.com/DO/flat/64.png",
  },
  {
    name: "Czech Republic (Czechia)",
    dialCode: "",
    code: "CZ",
    flag: "https://flagsapi.com/CZ/flat/64.png",
  },
  {
    name: "Central African Republic",
    dialCode: "+236",
    code: "KY",
    flag: "https://flagsapi.com/CF/flat/64.png",
  },
  {
    name: "Bahamas",
    dialCode: "+1242",
    code: "BS",
    flag: "https://flagsapi.com/BS/flat/64.png",
  },
  {
    name: "Costa Rica",
    dialCode: "+506",
    code: "CK",
    flag: "https://flagsapi.com/CR/flat/64.png",
  },
  {
    name: "Romania",
    dialCode: "+40",
    code: "RE",
    flag: "https://flagsapi.com/RE/flat/64.png",
  },
  {
    name: "Mongolia",
    dialCode: "+976",
    code: "MN",
    flag: "https://flagsapi.com/MN/flat/64.png",
  },
  {
    name: "Gabon",
    dialCode: "+241",
    code: "GA",
    flag: "https://flagsapi.com/GA/flat/64.png",
  },
  {
    name: "United Kingdom",
    dialCode: "+44",
    code: "GB",
    flag: "https://flagsapi.com/GB/flat/64.png",
  },
  {
    name: "Finland",
    dialCode: "+358",
    code: "FI",
    flag: "https://flagsapi.com/FI/flat/64.png",
  },
  {
    name: "Lebanon",
    dialCode: "+961",
    code: "LB",
    flag: "https://flagsapi.com/LB/flat/64.png",
  },
  {
    name: "Jersey",
    dialCode: "+44",
    code: "JE",
    flag: "https://flagsapi.com/JE/flat/64.png",
  },
  {
    name: "El Salvador",
    dialCode: "+503",
    code: "SV",
    flag: "https://flagsapi.com/SV/flat/64.png",
  },
  {
    name: "Haiti",
    dialCode: "+509",
    code: "HT",
    flag: "https://flagsapi.com/HT/flat/64.png",
  },
  {
    name: "Belize",
    dialCode: "+501",
    code: "BZ",
    flag: "https://flagsapi.com/BZ/flat/64.png",
  },
];
