export enum eModules {
  AssetsModule = "assets",
  OperatorsModule = "operators",
  UsersModule = "users",
  AirportsModule = "airports",
  FlightsModule = "flights",
  TicketsModule = "tickets",
  BookingsModule = "bookings",
  InvoicesModule = "invoices",
  QuotationsModule = "quotations",
  QuotationRequestsModule = "quotation-requests",
  AgenciesModule = "agencies",
  AuditLogsModule = "audit-logs",
  RolePermissionsModule = "role-permissions",
  DashboardsModule = "dashboards",
}
